// lib/countries.ts - Complete list of world countries

export interface Country {
    code: string // ISO 3166-1 alpha-3
    name: string
    continent: string
}

export const COUNTRIES: Country[] = [
    // Europa
    { code: 'ALB', name: 'Albania', continent: 'Europa' },
    { code: 'AND', name: 'Andorra', continent: 'Europa' },
    { code: 'AUT', name: 'Austria', continent: 'Europa' },
    { code: 'BLR', name: 'Bielorrusia', continent: 'Europa' },
    { code: 'BEL', name: 'Bélgica', continent: 'Europa' },
    { code: 'BIH', name: 'Bosnia y Herzegovina', continent: 'Europa' },
    { code: 'BGR', name: 'Bulgaria', continent: 'Europa' },
    { code: 'HRV', name: 'Croacia', continent: 'Europa' },
    { code: 'CYP', name: 'Chipre', continent: 'Europa' },
    { code: 'CZE', name: 'República Checa', continent: 'Europa' },
    { code: 'DNK', name: 'Dinamarca', continent: 'Europa' },
    { code: 'EST', name: 'Estonia', continent: 'Europa' },
    { code: 'FIN', name: 'Finlandia', continent: 'Europa' },
    { code: 'FRA', name: 'Francia', continent: 'Europa' },
    { code: 'DEU', name: 'Alemania', continent: 'Europa' },
    { code: 'GRC', name: 'Grecia', continent: 'Europa' },
    { code: 'HUN', name: 'Hungría', continent: 'Europa' },
    { code: 'ISL', name: 'Islandia', continent: 'Europa' },
    { code: 'IRL', name: 'Irlanda', continent: 'Europa' },
    { code: 'ITA', name: 'Italia', continent: 'Europa' },
    { code: 'XKX', name: 'Kosovo', continent: 'Europa' },
    { code: 'LVA', name: 'Letonia', continent: 'Europa' },
    { code: 'LIE', name: 'Liechtenstein', continent: 'Europa' },
    { code: 'LTU', name: 'Lituania', continent: 'Europa' },
    { code: 'LUX', name: 'Luxemburgo', continent: 'Europa' },
    { code: 'MKD', name: 'Macedonia del Norte', continent: 'Europa' },
    { code: 'MLT', name: 'Malta', continent: 'Europa' },
    { code: 'MDA', name: 'Moldavia', continent: 'Europa' },
    { code: 'MCO', name: 'Mónaco', continent: 'Europa' },
    { code: 'MNE', name: 'Montenegro', continent: 'Europa' },
    { code: 'NLD', name: 'Países Bajos', continent: 'Europa' },
    { code: 'NOR', name: 'Noruega', continent: 'Europa' },
    { code: 'POL', name: 'Polonia', continent: 'Europa' },
    { code: 'PRT', name: 'Portugal', continent: 'Europa' },
    { code: 'ROU', name: 'Rumanía', continent: 'Europa' },
    { code: 'RUS', name: 'Rusia', continent: 'Europa' },
    { code: 'SMR', name: 'San Marino', continent: 'Europa' },
    { code: 'SRB', name: 'Serbia', continent: 'Europa' },
    { code: 'SVK', name: 'Eslovaquia', continent: 'Europa' },
    { code: 'SVN', name: 'Eslovenia', continent: 'Europa' },
    { code: 'ESP', name: 'España', continent: 'Europa' },
    { code: 'SWE', name: 'Suecia', continent: 'Europa' },
    { code: 'CHE', name: 'Suiza', continent: 'Europa' },
    { code: 'UKR', name: 'Ucrania', continent: 'Europa' },
    { code: 'GBR', name: 'Reino Unido', continent: 'Europa' },
    { code: 'VAT', name: 'Ciudad del Vaticano', continent: 'Europa' },

    // Asia
    { code: 'AFG', name: 'Afganistán', continent: 'Asia' },
    { code: 'ARM', name: 'Armenia', continent: 'Asia' },
    { code: 'AZE', name: 'Azerbaiyán', continent: 'Asia' },
    { code: 'BHR', name: 'Baréin', continent: 'Asia' },
    { code: 'BGD', name: 'Bangladés', continent: 'Asia' },
    { code: 'BTN', name: 'Bután', continent: 'Asia' },
    { code: 'BRN', name: 'Brunéi', continent: 'Asia' },
    { code: 'KHM', name: 'Camboya', continent: 'Asia' },
    { code: 'CHN', name: 'China', continent: 'Asia' },
    { code: 'GEO', name: 'Georgia', continent: 'Asia' },
    { code: 'IND', name: 'India', continent: 'Asia' },
    { code: 'IDN', name: 'Indonesia', continent: 'Asia' },
    { code: 'IRN', name: 'Irán', continent: 'Asia' },
    { code: 'IRQ', name: 'Irak', continent: 'Asia' },
    { code: 'ISR', name: 'Israel', continent: 'Asia' },
    { code: 'JPN', name: 'Japón', continent: 'Asia' },
    { code: 'JOR', name: 'Jordania', continent: 'Asia' },
    { code: 'KAZ', name: 'Kazajistán', continent: 'Asia' },
    { code: 'KWT', name: 'Kuwait', continent: 'Asia' },
    { code: 'KGZ', name: 'Kirguistán', continent: 'Asia' },
    { code: 'LAO', name: 'Laos', continent: 'Asia' },
    { code: 'LBN', name: 'Líbano', continent: 'Asia' },
    { code: 'MYS', name: 'Malasia', continent: 'Asia' },
    { code: 'MDV', name: 'Maldivas', continent: 'Asia' },
    { code: 'MNG', name: 'Mongolia', continent: 'Asia' },
    { code: 'MMR', name: 'Myanmar', continent: 'Asia' },
    { code: 'NPL', name: 'Nepal', continent: 'Asia' },
    { code: 'PRK', name: 'Corea del Norte', continent: 'Asia' },
    { code: 'OMN', name: 'Omán', continent: 'Asia' },
    { code: 'PAK', name: 'Pakistán', continent: 'Asia' },
    { code: 'PSE', name: 'Palestina', continent: 'Asia' },
    { code: 'PHL', name: 'Filipinas', continent: 'Asia' },
    { code: 'QAT', name: 'Catar', continent: 'Asia' },
    { code: 'SAU', name: 'Arabia Saudita', continent: 'Asia' },
    { code: 'SGP', name: 'Singapur', continent: 'Asia' },
    { code: 'KOR', name: 'Corea del Sur', continent: 'Asia' },
    { code: 'LKA', name: 'Sri Lanka', continent: 'Asia' },
    { code: 'SYR', name: 'Siria', continent: 'Asia' },
    { code: 'TWN', name: 'Taiwán', continent: 'Asia' },
    { code: 'TJK', name: 'Tayikistán', continent: 'Asia' },
    { code: 'THA', name: 'Tailandia', continent: 'Asia' },
    { code: 'TLS', name: 'Timor Oriental', continent: 'Asia' },
    { code: 'TUR', name: 'Turquía', continent: 'Asia' },
    { code: 'TKM', name: 'Turkmenistán', continent: 'Asia' },
    { code: 'ARE', name: 'Emiratos Árabes Unidos', continent: 'Asia' },
    { code: 'UZB', name: 'Uzbekistán', continent: 'Asia' },
    { code: 'VNM', name: 'Vietnam', continent: 'Asia' },
    { code: 'YEM', name: 'Yemen', continent: 'Asia' },

    // África
    { code: 'DZA', name: 'Argelia', continent: 'África' },
    { code: 'AGO', name: 'Angola', continent: 'África' },
    { code: 'BEN', name: 'Benín', continent: 'África' },
    { code: 'BWA', name: 'Botsuana', continent: 'África' },
    { code: 'BFA', name: 'Burkina Faso', continent: 'África' },
    { code: 'BDI', name: 'Burundi', continent: 'África' },
    { code: 'CMR', name: 'Camerún', continent: 'África' },
    { code: 'CPV', name: 'Cabo Verde', continent: 'África' },
    { code: 'CAF', name: 'República Centroafricana', continent: 'África' },
    { code: 'TCD', name: 'Chad', continent: 'África' },
    { code: 'COM', name: 'Comoras', continent: 'África' },
    { code: 'COG', name: 'Congo', continent: 'África' },
    { code: 'COD', name: 'República Democrática del Congo', continent: 'África' },
    { code: 'CIV', name: 'Costa de Marfil', continent: 'África' },
    { code: 'DJI', name: 'Yibuti', continent: 'África' },
    { code: 'EGY', name: 'Egipto', continent: 'África' },
    { code: 'GNQ', name: 'Guinea Ecuatorial', continent: 'África' },
    { code: 'ERI', name: 'Eritrea', continent: 'África' },
    { code: 'ETH', name: 'Etiopía', continent: 'África' },
    { code: 'GAB', name: 'Gabón', continent: 'África' },
    { code: 'GMB', name: 'Gambia', continent: 'África' },
    { code: 'GHA', name: 'Ghana', continent: 'África' },
    { code: 'GIN', name: 'Guinea', continent: 'África' },
    { code: 'GNB', name: 'Guinea-Bisáu', continent: 'África' },
    { code: 'KEN', name: 'Kenia', continent: 'África' },
    { code: 'LSO', name: 'Lesoto', continent: 'África' },
    { code: 'LBR', name: 'Liberia', continent: 'África' },
    { code: 'LBY', name: 'Libia', continent: 'África' },
    { code: 'MDG', name: 'Madagascar', continent: 'África' },
    { code: 'MWI', name: 'Malaui', continent: 'África' },
    { code: 'MLI', name: 'Malí', continent: 'África' },
    { code: 'MRT', name: 'Mauritania', continent: 'África' },
    { code: 'MUS', name: 'Mauricio', continent: 'África' },
    { code: 'MAR', name: 'Marruecos', continent: 'África' },
    { code: 'MOZ', name: 'Mozambique', continent: 'África' },
    { code: 'NAM', name: 'Namibia', continent: 'África' },
    { code: 'NER', name: 'Níger', continent: 'África' },
    { code: 'NGA', name: 'Nigeria', continent: 'África' },
    { code: 'RWA', name: 'Ruanda', continent: 'África' },
    { code: 'STP', name: 'Santo Tomé y Príncipe', continent: 'África' },
    { code: 'SEN', name: 'Senegal', continent: 'África' },
    { code: 'SYC', name: 'Seychelles', continent: 'África' },
    { code: 'SLE', name: 'Sierra Leona', continent: 'África' },
    { code: 'SOM', name: 'Somalia', continent: 'África' },
    { code: 'ZAF', name: 'Sudáfrica', continent: 'África' },
    { code: 'SSD', name: 'Sudán del Sur', continent: 'África' },
    { code: 'SDN', name: 'Sudán', continent: 'África' },
    { code: 'SWZ', name: 'Esuatini', continent: 'África' },
    { code: 'TZA', name: 'Tanzania', continent: 'África' },
    { code: 'TGO', name: 'Togo', continent: 'África' },
    { code: 'TUN', name: 'Túnez', continent: 'África' },
    { code: 'UGA', name: 'Uganda', continent: 'África' },
    { code: 'ZMB', name: 'Zambia', continent: 'África' },
    { code: 'ZWE', name: 'Zimbabue', continent: 'África' },

    // América del Norte
    { code: 'ATG', name: 'Antigua y Barbuda', continent: 'América del Norte' },
    { code: 'BHS', name: 'Bahamas', continent: 'América del Norte' },
    { code: 'BRB', name: 'Barbados', continent: 'América del Norte' },
    { code: 'BLZ', name: 'Belice', continent: 'América del Norte' },
    { code: 'CAN', name: 'Canadá', continent: 'América del Norte' },
    { code: 'CRI', name: 'Costa Rica', continent: 'América del Norte' },
    { code: 'CUB', name: 'Cuba', continent: 'América del Norte' },
    { code: 'DMA', name: 'Dominica', continent: 'América del Norte' },
    { code: 'DOM', name: 'República Dominicana', continent: 'América del Norte' },
    { code: 'SLV', name: 'El Salvador', continent: 'América del Norte' },
    { code: 'GRD', name: 'Granada', continent: 'América del Norte' },
    { code: 'GTM', name: 'Guatemala', continent: 'América del Norte' },
    { code: 'HTI', name: 'Haití', continent: 'América del Norte' },
    { code: 'HND', name: 'Honduras', continent: 'América del Norte' },
    { code: 'JAM', name: 'Jamaica', continent: 'América del Norte' },
    { code: 'MEX', name: 'México', continent: 'América del Norte' },
    { code: 'NIC', name: 'Nicaragua', continent: 'América del Norte' },
    { code: 'PAN', name: 'Panamá', continent: 'América del Norte' },
    { code: 'KNA', name: 'San Cristóbal y Nieves', continent: 'América del Norte' },
    { code: 'LCA', name: 'Santa Lucía', continent: 'América del Norte' },
    { code: 'VCT', name: 'San Vicente y las Granadinas', continent: 'América del Norte' },
    { code: 'TTO', name: 'Trinidad y Tobago', continent: 'América del Norte' },
    { code: 'USA', name: 'Estados Unidos', continent: 'América del Norte' },

    // América del Sur
    { code: 'ARG', name: 'Argentina', continent: 'América del Sur' },
    { code: 'BOL', name: 'Bolivia', continent: 'América del Sur' },
    { code: 'BRA', name: 'Brasil', continent: 'América del Sur' },
    { code: 'CHL', name: 'Chile', continent: 'América del Sur' },
    { code: 'COL', name: 'Colombia', continent: 'América del Sur' },
    { code: 'ECU', name: 'Ecuador', continent: 'América del Sur' },
    { code: 'GUY', name: 'Guyana', continent: 'América del Sur' },
    { code: 'PRY', name: 'Paraguay', continent: 'América del Sur' },
    { code: 'PER', name: 'Perú', continent: 'América del Sur' },
    { code: 'SUR', name: 'Surinam', continent: 'América del Sur' },
    { code: 'URY', name: 'Uruguay', continent: 'América del Sur' },
    { code: 'VEN', name: 'Venezuela', continent: 'América del Sur' },

    // Oceanía
    { code: 'AUS', name: 'Australia', continent: 'Oceanía' },
    { code: 'FJI', name: 'Fiyi', continent: 'Oceanía' },
    { code: 'KIR', name: 'Kiribati', continent: 'Oceanía' },
    { code: 'MHL', name: 'Islas Marshall', continent: 'Oceanía' },
    { code: 'FSM', name: 'Micronesia', continent: 'Oceanía' },
    { code: 'NRU', name: 'Nauru', continent: 'Oceanía' },
    { code: 'NZL', name: 'Nueva Zelanda', continent: 'Oceanía' },
    { code: 'PLW', name: 'Palaos', continent: 'Oceanía' },
    { code: 'PNG', name: 'Papúa Nueva Guinea', continent: 'Oceanía' },
    { code: 'WSM', name: 'Samoa', continent: 'Oceanía' },
    { code: 'SLB', name: 'Islas Salomón', continent: 'Oceanía' },
    { code: 'TON', name: 'Tonga', continent: 'Oceanía' },
    { code: 'TUV', name: 'Tuvalu', continent: 'Oceanía' },
    { code: 'VUT', name: 'Vanuatu', continent: 'Oceanía' },
]

export const TOTAL_COUNTRIES = COUNTRIES.length

export const getCountryByCode = (code: string): Country | undefined => {
    return COUNTRIES.find(c => c.code === code)
}

export const getCountriesByContinent = (continent: string): Country[] => {
    return COUNTRIES.filter(c => c.continent === continent)
}

export const CONTINENTS = [
    'Europa',
    'Asia',
    'África',
    'América del Norte',
    'América del Sur',
    'Oceanía',
]

